platform :ios, ‘8.0’

target “learnDemo” do


pod 'WSProgressHUD'


pod 'AFNetworking', '~> 3.1.0'

pod 'YYCache', '~> 1.0.4'

pod 'IQKeyboardManager'  #0代码解决键盘遮挡输入框问题



pod 'YYModel'

pod 'RealReachability'

pod ‘BGFMDB’

end  
